// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "DBWorker.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::mancity;

class DBWorkerHandler : virtual public DBWorkerIf {
 public:
  DBWorkerHandler() {
    // Your initialization goes here
  }

  void ping() {
    // Your implementation goes here
    printf("ping\n");
  }

  void getAllMatches(MatchList& _return) {
    // Your implementation goes here
    printf("getAllMatches\n");
  }

  void getMatch(Match& _return, const int32_t matchId) {
    // Your implementation goes here
    printf("getMatch\n");
  }

  void getTeamName(std::string& _return, const int32_t teamId) {
    // Your implementation goes here
    printf("getTeamName\n");
  }

  void getTeamPlayers(PlayerList& _return, const int32_t teamId) {
    // Your implementation goes here
    printf("getTeamPlayers\n");
  }

  void getMatchEvents(EventList& _return, const int32_t matchId, const PlayerIdList& playerIdList, const EventTypeList& eventTypeList) {
    // Your implementation goes here
    printf("getMatchEvents\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<DBWorkerHandler> handler(new DBWorkerHandler());
  shared_ptr<TProcessor> processor(new DBWorkerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

