/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef mancity_CONSTANTS_H
#define mancity_CONSTANTS_H

#include "mancity_types.h"

namespace mancity {

class mancityConstants {
 public:
  mancityConstants();

};

extern const mancityConstants g_mancity_constants;

} // namespace

#endif
